payments-database:
  image: postgres:alpine
  restart: always
  hostname: payments-database
  ports:
    - "5432:5432"
  volumes:
    - /var/lib/postgresql/data
  environment:
    - POSTGRES_DB=${DB_NAME}
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
