version: '3'

services:

  payments-database:
    image: postgres
    restart: always
    hostname: payments-database
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  payments-app:
    build: .
    command: sh -c "python check_db.py --ip payments-database --port 5432 &&
                    python run.py"
    restart: always
    hostname: payments-app
    ports:
      - "5000:5000"
    depends_on:
      - payments-database
    environment:
      - LOCAL_DB=${LOCAL_DB}

